services:
  app:
    # image: python:3.12.5-alpine
    image: python@sha256:bb5d0ac04679d78a1258e7dfacdb4d9bdefe9a10480eaf9b4bb09445d076369f
    volumes:
      - .:/app
    command: "/app/src/run.sh"
    tty: true
    stdin_open: true
